name: Generate Snake Animation

# Run every 6 hours and allow manual trigger
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Generate the snake animation image from your contributions graph
      - uses: Platane/snk@v3
        id: snake
        with:
          # Use your GitHub username; you can use the context variable too.
          github_user_name: ${{ github.repository_owner }}
          # Specify the output file; here we’re generating an SVG.
          svg_out_path: dist/github-snake.svg
      
      # (Optional) Push the generated file to a branch (e.g., 'output')
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
