- name: Setup Git
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git fetch --unshallow  # Ensure all branches are available
    git checkout output || git checkout -b output  # Switch to output branch

- name: Commit and Push Changes
  run: |
    git add dist/snake.svg
    git commit -m "Updated snake animation" || echo "No changes to commit"
    git push origin output
